services:
  app:
    build: ./
    container_name: posts
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - posts_net


  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U yks" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      posts_net:
        aliases:
          - database


networks:
  posts_net: