// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputComment struct {
	Content string  `json:"content"`
	Post    string  `json:"post"`
	ReplyTo *string `json:"replyTo,omitempty"`
}

type InputPost struct {
	Name            string `json:"name"`
	Content         string `json:"content"`
	Author          string `json:"author"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
