// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputComment struct {
	Content string `json:"content"`
	Post    int    `json:"post"`
	ReplyTo *int   `json:"replyTo,omitempty"`
}

type InputPost struct {
	Name            string `json:"name"`
	Content         string `json:"content"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
