package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"posts/graph"
	"posts/internal/lib/pagination"
	"posts/internal/model"
)

// CreatePost is the resolver for the CreatePost field.
func (r *mutationResolver) CreatePost(ctx context.Context, post model.InputPost) (*model.Post, error) {
	newPost, err := r.PostsService.CreatePost(ctx, post.FromInput())
	if err != nil {
		//TODO: handle error
	}

	return &newPost, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, page *int, pageSize *int) ([]*model.Comment, error) {
	limit, offset := pagination.GetLimitAndOffset(page, pageSize)

	comments, err := r.CommentsService.GetCommentsByPost(ctx, obj.ID, limit, offset)
	if err != nil {
		//TODO: handle error
	}

	return comments, nil
}

// GetAllPosts is the resolver for the GetAllPosts field.
func (r *queryResolver) GetAllPosts(ctx context.Context, page *int, pageSize *int) ([]*model.Post, error) {

	limit, offset := pagination.GetLimitAndOffset(page, pageSize)

	posts, err := r.PostsService.GetAllPosts(ctx, limit, offset)
	if err != nil {
		//TODO: handle error
	}

	return posts, nil
}

// GetPostByID is the resolver for the GetPostById field.
func (r *queryResolver) GetPostByID(ctx context.Context, id int) (*model.Post, error) {
	post, err := r.PostsService.GetPostById(ctx, id)
	if err != nil {
		//TODO: handle error
	}

	return &post, nil
}

// Mutation returns graphql.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Post returns graphql.PostResolver implementation.
func (r *Resolver) Post() graph.PostResolver { return &postResolver{r} }

// Query returns graphql.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
